### ISSUE TITLE
Fatal error when requesting a deeplink without being logged in

### ISSUE THREAD

**Issue by michael-e** [TwistedInteractive/author_roles#2]
If you are not logged in to the Symphony backend and request a certain backend page (deeplink), e.g. `http://example.com/symphony/publish/news/edit/7869/saved/`, Symphony will normally show the login form. With Author Roles installed, a fatal error will occur instead:

> Fatal error: Call to a member function get() on a non-object in /var/www/example.com/extensions/author_roles/extension.driver.php on line 507

**Comment by kanduvisla** [comment]
Fixed in [this commit](https://github.com/kanduvisla/author_roles/commit/2f41a3d2671b4ce8a865fe9ecedb389d659ea663)
