### ISSUE TITLE
"Recoverable Errror" when deleting en author

### ISSUE THREAD

**Issue by michael-e** [TwistedInteractive/author_roles#3]
When attempting to delete a Symphony author I get the following "Symphony Recoverable Error":

```
Object of class Administration could not be converted to string
/var/www/maschine/extensions/author_roles/extension.driver.php line 128

123         $context = array($context);
124     }
125     // Delete the links:
126     foreach($context as $id_author)
127     {
128         Symphony::Database()->query('DELETE FROM `tbl_author_roles_authors` WHERE `id_author` = '.$id_author.';');
129     }
130 }
131 
132 /**
```

Deleting the author fails.

This error is independant of the author having a role assigned or not.

**Comment by kanduvisla** [comment]
Which version of Symphony are you using to produce this error?

**Comment by michael-e** [comment]
It's the current integration branch.

**Comment by kanduvisla** [comment]
That's the beta of 2.2.1 isn't it?

Haven't tested it with that one yet. Looks like the context of the  'AuthorPreDelete'-delegate is different in comparision with Symphony 2.2

**Comment by michael-e** [comment]
Please put this on hold. I will have to test again (because I can't repeat the issue at the moment).

**Comment by michael-e** [comment]
OK, I double-checked this: Deleting from the author index table works, but deleting from the author edit page does not.

It's the same in Symphhony 2.2!

**Comment by kanduvisla** [comment]
Fixed in [this commit](https://github.com/kanduvisla/author_roles/commit/06d114e563b0e08d6d5f5e8fcef42376b954df45)
