### ISSUE TITLE
Hiding fields is broken

### ISSUE THREAD

**Issue by michael-e** [TwistedInteractive/author_roles#5]
As [Cremol pointed out](http://symphony-cms.com/discuss/thread/62891/2/#position-27), hiding fields seems to be broken. I have verified the issue with the current Symphony integration branch.

**Comment by kanduvisla** [comment]
What field type are you trying to hide? And what version of Symphony are you using?

**Comment by michael-e** [comment]
A simple date field, for example. Symphony is (as posted above):

> current Symphony integration branch

Could it be that hiding does not work for developer accounts?

**Comment by michael-e** [comment]
I checked this with an author account. Hiding sections works, but hiding fields does not. 

For developers everything will be visible (no matter which author role they have); is that the correct behaviour?

**Comment by kanduvisla** [comment]
Yes, for developers everything is visible. The roles will only apply to authors (hence the name 'Author Roles' ;-))

I'll look into it.

**Comment by iwyg** [comment]
I think this is directly connected to this issue. 
Is the `role_model.js` is missing in the asset folder, so hiding fileds won't work.

change line 449 form `$context['oPage']->addScriptToHead(URL.'/extensions/role_model/assets/role_model.js');` to `$context['oPage']->addScriptToHead(URL.'/extensions/author_roles/assets/author_roles.js');`

**Comment by kanduvisla** [comment]
fixed
