### ISSUE TITLE
Layout Bug when both Editing and Creating Entry are disabled

### ISSUE THREAD

**Issue by iwyg** [TwistedInteractive/author_roles#6]
When disabling both editing and creating entries the wohle `div.action` is removed,  causing the footer not to be sticky to the bottom (body height is collapsing to window height and not to the full content height).

Should be fixed easily.

**Comment by kanduvisla** [comment]
Just tested this in S2.2.5. Does this bug still occur?

**Comment by kanduvisla** [comment]
Closing this since there is no footer left in S2.3, and for older versions of Symphony it seems like an edge case
