### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by kirkstrobeck** [TwistedInteractive/author_roles#7]
If author has a default login section and it is `access denied` it doesn't redirect to an available section..

**Comment by kanduvisla** [comment]
Does it display the section which should be hidden?

**Comment by kanduvisla** [comment]
Not a bug, since this is also mentioned in the message below assigning a role to an author:

> Please note: According to the role you selected, some sections may not be visible to this author. If the Default Area of this author is set to one of these hidden sections, it will result in an authorization error message when he or she logs in. Be aware to set the Default Area to an area the author is allowed to see.

**Comment by kirkstrobeck** [comment]
It would be a helpful feature, not saying it is a bug..
